# MIT License
#
# (C) Copyright [2022] Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

version: '3.7'

networks:
  smd:

services:
  tftp-server:
    container_name: tftp-server
    hostname: tftp-server
    image: bikeshack/tftp-server:v1.1
    network_mode: "host"
  dhcpd-server:
    container_name: dhcpd-server
    hostname: dhcpd
    image: docker.io/networkboot/dhcpd:latest
    network_mode: "host"
    volumes:
      - /data/dhcpd:/data
  postgres:
    container_name: smd-postgres
    hostname: postgres
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=hmsdsuser
      - POSTGRES_USER=hmsdsuser
      - POSTGRES_DB=hmsds
    ports:
      - "5432:5432"
    networks:
      - smd
  smd-init:
    container_name: smd-init
    image: docker.io/bikeshack/smd:v2.12.0
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    hostname: smd-init
    depends_on:
      - postgres
    networks:
      - smd
    entrypoint:
      - /usr/local/bin/smd-init 
      - -dbhost=postgres
  smd:
    container_name: smd
    image: docker.io/bikeshack/smd:v2.12.0
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    hostname: smd
    depends_on:
      - postgres
      - smd-init
    ports:
      - "27779:27779"
    networks:
      - smd
